### ISSUE TITLE
使用gg和bb要求它使用谷歌或bing时，回复为ddg:10 bing:10 google :10

### ISSUE THREAD

**Issue by AdikiaF** [Xueheng-Li/SynologyChatbotGPT#10]
使用gg和bb要求它使用谷歌或bing时，回复为ddg:10 bing:10 google :10

**Comment by Xueheng-Li** [comment]
显示的是对的，引导词gg 和 bb 没有任何区别，默认都是会同时使用 ddg, bing和 google 搜一遍。
