### ISSUE TITLE
输出代码的时候无法显示

### ISSUE THREAD

**Issue by vivagonna** [Xueheng-Li/SynologyChatbotGPT#11]
例如：

```
写一段python代码，计算100以内的质数
ChatGPT [聊天机器人]18:06
...
ChatGPT [聊天机器人]18:06(仅对您可见)
无法向机器人服务器发送请求。请联系机器人拥有者
```

**Comment by vivagonna** [comment]
后台log里面chatgpt返回的信息是正常的

**Comment by Xueheng-Li** [comment]
更新了v1.1.0，修复这个bug，你用最新的版本再试一下。

**Comment by Xueheng-Li** [comment]
> 更新了v1.1.0，修复这个bug，你用最新的版本再试一下。

记得在settings.py改为stream=False

**Comment by Xueheng-Li** [comment]
> 后台log里面chatgpt返回的信息是正常的

用最新的版本再试一下，记得在settings.py中改为stream=False

**Comment by vivagonna** [comment]
感谢更新 不过似乎还是不行，会触发”无法向机器人服务器发送请求。请联系机器人拥有者。“

**Comment by vivagonna** [comment]
> > 后台log里面chatgpt返回的信息是正常的
> 
> 用最新的版本再试一下，记得在settings.py中改为stream=False

没看到这个 我试下

**Comment by vivagonna** [comment]
怪了 还是显示不出来，客户端和网页都是。 

另外v1.1.0的 talentbot 似乎有个bug，`name 'system_prompt' is not defined`

**Comment by Xueheng-Li** [comment]
> 怪了 还是显示不出来，客户端和网页都是。
> 
> 另外v1.1.0的 talentbot 似乎有个bug，`name 'system_prompt' is not defined`

不好意思，settings.py也更新了，原来的chatbotcharactor变量名改为了`system_prompt`，请用新的`settings.py`再试一下。另外，你在测试的时候看看后台信息，群晖 chat 前端的提示”无法向机器人服务器发送请求。请联系机器人拥有者“是没什么意义的，即使后台运行一切正常，群晖也可能会出现这个信息。

**Comment by vivagonna** [comment]
测试了一下好像是特点的字符或代码触发的，比如

”写一段python代码 生成1-00的随机数“ 能成功返回代码和信息

而 ”写一段python代码 计算100以内的质数“ 不能

后台log是这样的：

messages: [{'role': 'system', 'content': '你是ChatGPT机器人，一名智能助手。你的使命是尽可能地用详尽的、温暖的、友善的话语帮助我和我的家人，在各种方面提供帮助和支持。无论我需要什么帮助或建议，你都会尽力提供详尽信息。'}, {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': '你好！我是ChatGPT机器人，很高兴能为您提供帮助和支持。请告诉我您需要什么帮助或建议，我会尽力为您提供详尽信息。'}, {'role': 'user', 'content': '写一段python代码 计算100以内的质数'}, {'role': 'user', 'content': '不写了'}]
好的，如果您需要任何帮助，请随时联系我。
好的，以下是一段Python代码，可以计算100以内的质数：

```python
primes = []
for num in range(2, 101):
    is_prime = True
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            is_prime = False
            break
    if is_prime:
        primes.append(num)

print(primes)
```

代码解释：

首先，我们创建一个空列表 `primes`，用于存储所有的质数。

然后，我们使用 `range()` 函数生成从 2 到 100 的所有整数，因为质数定义为大于 1 的整数。

接下来，我们使用一个布尔变量 `is_prime` 来表示当前的数字是否为质数。我们将其初始化为 `True`，然后使用一个嵌套的循环来检查当前数字是否能被 2 到其平方根之间的任何整数整除。如果它能被整除，那么它不是质数，我们将 `is_prime` 设置为 `False` 并退出内部循环。

最后，如果 `is_prime` 仍然为 `True`，那么当前数字是质数，我们将其添加到 `primes` 列表中。

最后，我们打印出 `primes` 列表，其中包含所有的质数。

**Comment by Xueheng-Li** [comment]
> 

你“好的，以下是一段Python代码……”这段信息群晖能收到吗？是完全收不到，还是只是没有执行代码的 output（“运行结果：……”）？如果只是没有执行结果，而你说的生产随机数的代码能被执行，那么问题应该只是在 gpt 回复内容中的代码块处没有标明是python代码……

**Comment by Xueheng-Li** [comment]
我这边可以正常生成代码并执行（其中插入的“运行结果：……”就是服务器本地执行的结果）：

 
 
 
在 2023-04-15 12:15，vivagonna  ***@***.***>  写到：
>
> 测试了一下好像是特点的字符或代码触发的，比如
>
>
> ”写一段python代码 生成1-00的随机数“ 能成功返回代码和信息
>
>
> 而 ”写一段python代码 计算100以内的质数“ 不能
>
>
> 后台log是这样的：
>
>
> messages: [{'role': 'system', 'content': '你是ChatGPT机器人，一名智能助手。你的使命是尽可能地用详尽的、温暖的、友善的话语帮助我和我的家人，在各种方面提供帮助和支持。无论我需要什么帮助或建议，你都会尽力提供详尽信息。'}, {'role': 'user', 'content': '你好'}, {'role': 'assistant', 'content': '你好！我是ChatGPT机器人，很高兴能为您提供帮助和支持。请告诉我您需要什么帮助或建议，我会尽力为您提供详尽信息。'}, {'role': 'user', 'content': '写一段python代码 计算100以内的质数'}, {'role': 'user', 'content': '不写了'}]
>   
好的，如果您需要任何帮助，请随时联系我。
>   
好的，以下是一段Python代码，可以计算100以内的质数：
>
> primes   =  []
 for   num   in   range(2,  101):
     is_prime   =   True   
     for   i   in   range(2,  int(num   **   0.5)  +   1):
         if   num   %   i   ==   0:
             is_prime   =   False   
             break   
     if   is_prime:
         primes.append(num)

 print(primes)
