### ISSUE TITLE
Very slow when the server is ran on the same NAS

### ISSUE THREAD

**Issue by mcurti** [Xueheng-Li/SynologyChatbotGPT#13]
When I run the basicBot.py on synology itself it eats up a lot of I/O waiting and my NAS is lagging enormously. I did not change anything in the settings.py, I use all entries as they are by default, can it be that I miss some configurations?

**Comment by Xueheng-Li** [comment]
Are you sure that it takes up a lot of I/O? It may be slow, and sometimes even fail to connect to the openai api, but not because there is problem on the server side; it is slow usually due to the Internet connection issue.

**Comment by mcurti** [comment]
Indeed. The problem is in the chat app. It takes a lot of time to start up and process the requests. I guess my NAS is slow in general.

**Comment by Xueheng-Li** [comment]
> Indeed. The problem is in the chat app. It takes a lot of time to start up and process the requests. I guess my NAS is slow in general.

I don’t see a reason why this might be the case given that you are using the basicBot. What the basicBot does is simply sending a request to the openai and get the response…
