### ISSUE TITLE
无法向机器人服务器发送请求。请联系机器人拥有者

### ISSUE THREAD

**Issue by flyfox666** [Xueheng-Li/SynologyChatbotGPT#17]
![image](https://user-images.githubusercontent.com/121539277/233770759-35501355-bb24-4eca-b8ee-e49d499cdf07.png)
已经docer里面加了变量了。为啥还不行

**Comment by flyfox666** [comment]
![image](https://user-images.githubusercontent.com/121539277/233772150-c5004fa4-1675-4c73-bdb7-578ab94a637d.png)

**Comment by Xueheng-Li** [comment]
确定https://192.168.86.59…. 还是http://…?

**Comment by flyfox666** [comment]
> 确定是[https://192.168.86.59….吗？](https://192.168.86.59%E2%80%A6.%E5%90%97%EF%BC%9F) 还是http://…?

这个就是我跟着教程从ds chat 里的设置里弄出来的，我是在群晖上做的docker

**Comment by flyfox666** [comment]
Error sending message to Synology Chat: HTTPConnectionPool(host='192.168.86.59', port=1984): Max retries exceeded with url: /webapi/entry.cgi?api=SYNO.Chat.External&method=chatbot&version=2&token=%22AX89ta6nwcJNbHctotkakm9jL9bLVxDSz5F3qq0mhSCwIjQhq83yfhvjNiD2p7G7%22 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fd366706200>, 'Connection to 192.168.86.59 timed out. (connect timeout=None)'))
现在的报错是这个

**Comment by Xueheng-Li** [comment]
群晖那边有收到省略号“…”吗？

**Comment by flyfox666** [comment]
没有收到省略号

**Comment by flyfox666** [comment]
![image](https://user-images.githubusercontent.com/121539277/233794024-ab79dbab-cb90-4bda-ad2f-33d54f75dbf5.png)

**Comment by Xueheng-Li** [comment]
那就是还是没能连接到群晖，应该还是incoming webhook url没填对。

**Comment by flyfox666** [comment]
![image](https://user-images.githubusercontent.com/121539277/233794754-a797565c-6f7e-4ec2-930b-f1839b5526b0.png)
![image](https://user-images.githubusercontent.com/121539277/233794765-9653e743-f582-4be5-bedb-49fa97a4c5ca.png)
用了quickconnect的登陆试了下，后台我看了答案已经得到了，也没跳error，但是。。。chat里就是不行

**Comment by Xueheng-Li** [comment]
> ![image](https://user-images.githubusercontent.com/121539277/233794754-a797565c-6f7e-4ec2-930b-f1839b5526b0.png) ![image](https://user-images.githubusercontent.com/121539277/233794765-9653e743-f582-4be5-bedb-49fa97a4c5ca.png) 用了quickconnect的登陆试了下，后台我看了答案已经得到了，也没跳error，但是。。。chat里就是不行

quickconnect 应该是不行的，如果这个 docker 就在跑在同一台群晖上，那么试试把incoming webhook url改为：`http://127.0.0.1:1984/webapi/entry.cgi?api=SYNO.Chat.External&method=chatbot&version=2&token=%22AX89ta6nwcJNbHctotkakm9jL9bLVxDSz5F3qq0mhSCwIjQhq83yfhvjNiD2p7G7%22` 或者 `https://127.0.0.1:1984/webapi/entry.cgi?api=SYNO.Chat.External&method=chatbot&version=2&token=%22AX89ta6nwcJNbHctotkakm9jL9bLVxDSz5F3qq0mhSCwIjQhq83yfhvjNiD2p7G7%22` 试试

**Comment by flyfox666** [comment]
hi ,省略号收到啦。最后用外网vps穿透进去做了个chat链接就好了。感谢啦

**Comment by sunnywinter81** [comment]
> hi ,省略号收到啦。最后用外网vps穿透进去做了个chat链接就好了。感谢啦

能具体说一下吗？
我也是同样问题，没有解决方案

**Comment by flyfox666** [comment]
> > hi ,省略号收到啦。最后用外网vps穿透进去做了个chat链接就好了。感谢啦
> 
> 
> 
> 能具体说一下吗？
> 
> 我也是同样问题，没有解决方案

用cloudflare tunnel 做一个内网的域名链接
