### ISSUE TITLE
docker终端提示 IndexError

### ISSUE THREAD

**Issue by zhang-qihao** [Xueheng-Li/SynologyChatbotGPT#34]
![Uploading a0d9d9efc77a6b2d3633609a8965520d.jpeg…]()

**Comment by zhang-qihao** [comment]
![Uploading a0d9d9efc77a6b2d3633609a8965520d.jpeg…]()

**Comment by hhhguany** [comment]
发现一种粗暴的解决方案，添加`stream=False`即可。但是就不能一条一条出回答了。希望开发者能尽快修复下。

**Comment by hhhguany** [comment]
我尝试进行了修复：https://github.com/Xueheng-Li/SynologyChatbotGPT/pull/35
