### ISSUE TITLE
运行py提示出错，Use a production WSGI server instead

### ISSUE THREAD

**Issue by yzlyu** [Xueheng-Li/SynologyChatbotGPT#7]
你好， 
环境：pve装的debian 11，python 3.9
运行 talentBot.py 显示信息如下：
NFO:llama_index.token_counter.token_counter:> [build_index_from_documents] Total LLM token usage: 0 tokens
INFO:llama_index.token_counter.token_counter:> [build_index_from_documents] Total embedding token usage: 0 tokens
 * Serving Flask app 'talentBot'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.

该如何解决呢？麻烦了，谢谢。

**Comment by Xueheng-Li** [comment]
你遇到的问题是什么？你写的后台显示的这几行表示已经成功启动了啊。

**Comment by yzlyu** [comment]
> 你遇到的问题是什么？你写的后台显示的这几行表示已经成功启动了啊。这几行没有一条是错误信息。

抱歉 是我理解的问题，我以为按ctrl+c会后台运行，原来是把程序给杀掉啦～～
可以正常运行 完全没问题～～ 谢谢大佬～～
