### ISSUE TITLE
搜索引擎功能無法使用

### ISSUE THREAD

**Issue by asdfgh282812** [Xueheng-Li/SynologyChatbotGPT#8]
謝謝各位開發這個功能，畢竟synoogychat很冷門，萬分感謝

在第五點的「具备使用搜索引擎（Google, Bing, Baidu, DuckDuckGo）搜索最新网络信息回答问题的能力，用关键词bb或gg开头即可实时搜索网络信息」
我嘗試使用google 或bing輸入詞，只會出現數字，如下：
![image](https://user-images.githubusercontent.com/105690967/229583809-ab51b422-26a0-41df-b507-80be5f95721a.png)

請問是為什麼呢？
相關錯誤訊息如圖：
![image](https://user-images.githubusercontent.com/105690967/229584310-02680f68-dd17-4de8-9f30-d599c91f40b3.png)

謝謝解答

**Comment by Xueheng-Li** [comment]
你试试一下排查步骤：
1、先确认是不是在代码所在目录运行`python talentBot.py`，如果不是的话先进入到代码所在目录，再重新尝试运行`python talentBot.py`；
2、如果已经是在代码所有目录运行程序，那么查看下代码所在目录有没有自动生成`searchResults` 这个文件夹，如果没有就手动创建一个，再重新尝试运行。如果`searchResults` 文件夹已经存在，就进去看看能不能找到你之前运行时产生过的这个`d8....7c.txt`这个文档，如果有的话，讲明之前的搜索和索引过程都在正常运行了，已经能够正常调用搜索引擎并保存搜索结果文档了，那么问题应该出在读取搜索结果文档的权限上。

**Comment by asdfgh282812** [comment]
您好，謝謝您的回答，確定是因為沒有searchResults 這個資料夾所以功能無法使用，已解決
